---
- name: Provision an Ansible Control Node, 3 Tower Servers, and an RDS Database
  hosts: localhost
  connection: local
  roles:
    - { role: provision }
  
  post_tasks:
    - name: Wait for SSH to come up on the Control Node
      delegate_to: "{{ item }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ groups['control'] }}"
      tags: control    

- name: Boostrap the Control Node to administer the Tower installation
  hosts: control
  roles:
    - { role: bootstrapControl }
